### ISSUE TITLE
Error in fixture

### ISSUE THREAD

**Issue by earona** [robproject/fsjd#16]
Hi, I'm getting an error on line 379 when processing a fixture.
The original fixture contained: 
`
[
] 
`
the new one contains: 
`[
 {
  "default_value": null,
  "doc_type": "Supplier",
  "docstatus": 0,
  "doctype": "Property Setter",
  "doctype_or_field": "DocField",
  "field_name": "tax_id",
  "is_system_generated": 0,
  "modified": "2024-08-22 15:42:38.733401",
  "module": "AFIP",
  "name": "Supplier-tax_id-reqd",
  "property": "reqd",
  "property_type": "Check",
  "row_name": null,
  "value": "1"
 },
 {
  "default_value": "0",
  "doc_type": "Customer",
  "docstatus": 0,
  "doctype": "Property Setter",
  "doctype_or_field": "DocField",
  "field_name": "tax_id",
  "is_system_generated": 0,
  "modified": "2024-08-22 16:13:07.979467",
  "module": "AFIP",
  "name": "Customer-tax_id-reqd",
  "property": "reqd",
  "property_type": "Check",
  "row_name": "",
  "value": "1"
 }
]`

By the way, it's a property setter fixture.

**Comment by earona** [comment]
Solved.

I would like to take this opportunity to congratulate you on the excellent work.

**Comment by robproject** [comment]
@earona thank you and thanks for pointing this out!
